name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        run: npm install
      - run: npm run build --if-present
      - run: exit 0
      - run: npm test
      - run: exit 0
      - run: killall node
      - run: npm run dev
      - id: instal

      - name: Send email if failure
        if: steps.instal.outcome != 'failure'
        run: exit 1